import os
API_TOKEN = os.getenv('API_TOKEN')
API_USER = os.getenv('API_USER')
KAYAKO_USER = os.getenv('KAYAKO_USER')
KAYAKO_PASSWORD = os.getenv('KAYAKO_PASSWORD')
KAYAKO_API_ENDPOINT = os.getenv('KAYAKO_API_ENDPOINT')
DIALOGFLOW_PROJECT_ID = os.getenv('DIALOGFLOW_PROJECT_ID')
